Support substitution of vscode variables in ctestPath like in cmakePath
microsoft/vscode-cmake-tools pull request #1710
Opened 2021-03-10 16:29 UTC by FakeTruth

## This change addresses item #785

### This changes ctestPath behavior

The following changes are proposed:

- Substitute VSCode variables for ctestPath in the same way as for cmakePath.

## The purpose of this change

Enables users to use variables like `${workspaceFolder}` in their ctestPath. cmakePath already allows this.

2021-03-15 22:04 UTC, elahehrashedi requested changes

2021-03-18 17:07 UTC, FakeTruth commented on src/paths.ts
> +  async expandStringWithVSCodeVars(tmpl: string, wsc: DirectoryContext): Promise<string> {
Thanks for the review, I've updated the pull request

2021-03-18 18:35 UTC, elahehrashedi approved these changes

2021-03-18 18:38 UTC, elahehrashedi commented on src/paths.ts
> +  async expandStringWithVSCodeVars(tmpl: string, wsc: DirectoryContext): Promise<string> {
@FakeTruth Thank you for your prompt response. I approved your PR. Please merge your PR by clicking on "Merge Pull Request" green button in below.

2021-03-18 18:46 UTC, FakeTruth commented on src/paths.ts
> +  async expandStringWithVSCodeVars(tmpl: string, wsc: DirectoryContext): Promise<string> {
Thanks approval, unfortunately there's no merge button for me. It says:
`Only those with write access to this repository can merge pull requests.`

2021-03-18 18:53 UTC, merged

2021-03-18 18:53 UTC, bobbrow commented on src/paths.ts
> +  async expandStringWithVSCodeVars(tmpl: string, wsc: DirectoryContext): Promise<string> {
I merged it.