Add support for CMake Presets V5
microsoft/vscode-cmake-tools pull request #2995
Opened 2023-02-02 19:38 UTC by nasinlock

## This change addresses item #[[2979]]

The following changes are proposed:

- Add support for the 'test output truncation' feature
- Add support for the 'path list separator macro.

## Other Notes/Information

Updates to the tests to account for these new features will be added in a second pull request.

2023-02-02 20:04 UTC, bobbrow requested changes

2023-02-02 20:04 UTC, bobbrow commented on test/extension-tests/successful-build/test/variable-substitution.test.ts
> +        cacheEntry = cache.get('pathListSep') as CacheEntry;
I think you should revert the changes to this test file.  pathListSep only exists in the context of presets, it's not something you can use for substitution in the settings.

2023-02-02 20:04 UTC, bobbrow commented on CHANGELOG.md
> +- Add support for CMake Presets V5 [#2979](https://github.com/microsoft/vscode-cmake-tools/issues/2979)
nit: please add a period at the end of the sentence.

2023-02-02 20:31 UTC, nasinlock commented on src/cmakeProject.ts
> +                (await fs.walk(searchRoot)).forEach((e: any) => {
I was getting an error reported for that line. I'll remove the change and see if it re-appears.

2023-02-02 21:54 UTC, nasinlock commented on src/preset.ts
> +        expansionOpts.vars['pathListSep'] = '${pathListSep}';
That makes sense. I thought in VSCode we let CMake handle the macro expansion. I'll update to do the expansion ourselves

2023-02-02 22:05 UTC, nasinlock commented on src/preset.ts
> +        expansionOpts.vars['pathListSep'] = '${pathListSep}';
Updated

2023-02-02 23:29 UTC, bobbrow commented on test/extension-tests/successful-build/test/variable-substitution.test.ts
> +                pathListSep: '${pathListSep}'
revert this case too

2023-02-03 02:14 UTC, elahehrashedi approved these changes

2023-02-03 15:51 UTC, bobbrow approved these changes

2023-02-03 15:51 UTC, merged