Fix test explorer hang
microsoft/vscode-cmake-tools pull request #3163
Opened 2023-05-05 03:54 UTC by xisui-MSFT

Fix issue #3154, and show a test preset picker when it's not set when running tests.

2023-05-05 16:24 UTC, benmcmorran requested changes
The code changes look good to me. Can you add an entry to the changelog for this bug fix and for the fix in #3160? You'll need to add a new section at the top of the changelog for version 1.15 since we released version 1.14.31 earlier this week.

2023-05-08 19:29 UTC, benmcmorran approved these changes

2023-05-08 19:29 UTC, merged

2023-05-12 22:43 UTC, bobbrow commented
I am getting prompted to select a test preset every time I open my folder.  Is this being called too early?

2023-05-12 23:25 UTC, xisui-MSFT commented
The fix executes the extension command and doesn't call a function. So the preset should be saved. I'll try to repro.

Thanks,
Xinyu Sui
________________________________
From: Bob Brown ***@***.***>
Sent: Friday, May 12, 2023 3:43 PM
To: microsoft/vscode-cmake-tools ***@***.***>
Cc: Xinyu Sui ***@***.***>; Author ***@***.***>
Subject: Re: [microsoft/vscode-cmake-tools] Fix test explorer hang (PR #3163)


I am getting prompted to select a test preset every time I open my folder. Is this being called too early?

—
Reply to this email directly, view it on GitHub<https://github.com/microsoft/vscode-cmake-tools/pull/3163#issuecomment-1546395547>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AKQPSC3KE3PABCEX67VFURDXF24JVANCNFSM6AAAAAAXWTDAZQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>