Improve test case failure/skip states and their output (#4116)
microsoft/vscode-cmake-tools pull request #4129
Opened 2024-10-15 17:05 UTC by redstrate

## This change addresses item #4116

### This changes visible test output

The following changes are proposed:

- Change the test output message when encountering an error exit code.
- Check for skipped tests and mark them as skipped.

## The purpose of this change

Currently if a test fails, it's not immediately clear why that is because we give the exit code - and not the output from ctest. That is now fixed and the ctest output is shown which greatly improves the usefulness of the Test Results pane and other places where this output is shown like Code Lens.

Skipped test cases were also not actually marked as skipped, and that is now fixed as well.

## Other Notes/Information

Comparison screenshots to show the improvement:

### Failed Tests

| Before | After |
| --- | --- |
| ![Screenshot_20241015_125716](https://github.com/user-attachments/assets/fcdde96c-e788-4988-8ccc-f09be1cbaebb) | ![Screenshot_20241015_125209](https://github.com/user-attachments/assets/6b32880b-b676-4fe0-9cc9-46207d1e7216) |

### Skipped Tests

| Before | After |
| --- | --- |
| ![Screenshot_20241015_125700](https://github.com/user-attachments/assets/1d4815d0-80cd-4a30-87f9-ab56a2320a6b) | ![Screenshot_20241015_125759](https://github.com/user-attachments/assets/3df709b6-e5fb-409d-b726-160dd0a33e01) |

Unfortunately this google test example I used doesn't set test source location, but if it did then code lens would be affected as well like in this outdated screenshot from the issue:

![image](https://github.com/user-attachments/assets/f8435712-6667-4ea6-bac2-d7edf91e84d9)

2024-10-15 17:27 UTC, redstrate commented
@microsoft-github-policy-service agree company="KDAB"

2024-10-16 17:08 UTC, gcampbell-msft requested changes
@redstrate This looks great! 

If you could please make a CHANGELOG entry, then we can approve and accept this PR! Thanks.

2024-10-16 21:22 UTC, redstrate commented
> @redstrate This looks great!
> 
> If you could please make a CHANGELOG entry, then we can approve and accept this PR! Thanks.

Done!

2024-10-17 12:49 UTC, gcampbell-msft approved these changes

2024-10-17 18:02 UTC, gcampbell-msft commented on src/ctest.ts
> +                if (completionStatus == "SKIP_REGULAR_EXPRESSION_MATCHED") {
Needs to be `===` instead of `==`. Thanks.

2024-10-21 16:34 UTC, gcampbell-msft requested changes
See other comments.

2024-11-08 19:52 UTC, gcampbell-msft approved these changes

2024-11-11 14:09 UTC, merged