Add end to end test devoted to ctest
microsoft/vscode-cmake-tools pull request #4186
Opened 2024-11-24 10:30 UTC by hippo91

### This changes test system

The following changes are proposed:

This PR is a proposal to add end to end test devoted to ctest part of the extension.

It adds a directory named `single-root-ctest` in the `end-to-end-tests` directory.

It also changes slightly the source directory in order:
  - to avoid early return in the `refreshTests` method (`ctest.ts` file) when in testing mode;
  - to change the return code of the `ctest` method (cmakeProject.ts) so that successfull test return 0 and failure returns -1.

## The purpose of this change

When doing change to the `ctest` part of the extension, i did not feel very comfortable not being backed up by tests.
This PR tries to circumvent this.

2025-03-07 17:02 UTC, gcampbell-msft requested changes
I haven't reviewed the test project itself yet, I hope to get to it later today or next week, but I have some feedback now that could be addressed. 

Also, it is **essential** that this test gets added to the PR tests, like here: https://github.com/microsoft/vscode-cmake-tools/blob/5107f7edfb4a748c0ef1606bf4db2a2f54cb491e/.github/workflows/ci-main.win.yml#L51C4-L58C28

2025-03-07 17:06 UTC, gcampbell-msft commented on test/end-to-end-tests/single-root-ctest/project-folder/CMakePresets.json
> +      "cacheVariables": {
We need to ensure that we define the CMAKE_C_COMPILER and CMAKE_CXX_COMPILER, depending on what OS this is run on.

2025-03-07 17:10 UTC, gcampbell-msft commented
@hippo91 I apologize for taking so long to start reviewing these, we appreciate your patience. 

We GREATLY appreciate your contribution to our engineering system, so we'd love to work with you and iterate on this PR to make these testing contributions, 

A couple of things: 
1. These tests should be integrated into our PR build pipelines so that we can test them in each PR
2. To do that, they should be set up to be cross-platform so that they can be run on each platform, since ctest is available on all three OS's. This will require modifications to the presets to define things like the CMAKE_C_COMPILER, CMAKE_CXX_COMPILER, and possibly using different generators on each OS. 
3. Currently, are you able to get these to work locally on Windows? I notice that I hit errors when trying to open and run in Windows. 

Again, we greatly appreciate this contribution and hope to iterate on the PR with you so that we can improve our engineering system. 

Thanks! Let us know if you have any questions.

2025-03-08 15:22 UTC, hippo91 commented on .vscode/launch.json
> +                "${workspaceFolder}/dist/**/*.js",
@gcampbell-msft you are right it was an error.

2025-03-22 12:14 UTC, hippo91 commented on src/cmakeProject.ts
> +        return (retc === 0) ? 0 : -1;
@gcampbell-msft i did change to keep integrity of the return code in the `ctest` method.

I am not confident to do the same change in the `cpack` method because i do not know how to check the result.

2025-03-22 12:16 UTC, hippo91 commented on test/end-to-end-tests/single-root-ctest/project-folder/CMakePresets.json
> +  "version": 2,
:+1:

2025-03-22 12:20 UTC, hippo91 commented on test/end-to-end-tests/single-root-ctest/project-folder/test_utils.cpp
> +int generic_test(const std::string& test_filepath, const bool success) {
:+1:

2025-03-22 13:57 UTC, hippo91 commented on test/end-to-end-tests/single-root-ctest/project-folder/CMakePresets.json
> +      "cacheVariables": {
@gcampbell-msft i added hidden configure preset that hold compiler specifications for linux and windows systems. These presets are then mixed up with those setting up the tests to have all cases covered.

2025-03-22 14:29 UTC, hippo91 commented
@gcampbell-msft i integrated these tests in the PR build pipelines.

I configured C and CXX compilers for linux and windows systems. I do not have any windows os at home so i'm not able to test that. Neither can i on Mac OS. I was counting on the CI to check that.

2025-04-05 10:30 UTC, hippo91 commented
@gcampbell-msft i tried to debug the failing CI tests but was unable to understand what was failing in the build step.

I suppose this is the build of the C++ test project but cannot confirm.
For now i try to run the CI locally using `act`. If you have any idea or hint about how i can debug the CI i'll be happy to try them.

2025-04-12 10:54 UTC, hippo91 commented
@gcampbell-msft i am trying to investigate but i do not know how i can have access to build output or log. Have you got any idea?
Another approach that i'am trying is to run the CI locally thanks to `act`. Maybe is there another possibility?

2025-04-14 12:47 UTC, gcampbell-msft commented
@hippo91 Are you not able to view the build log if you click on the github links? 

Our CI pipelines run publicly in github. Here is a link to the Windows one, for example, https://github.com/microsoft/vscode-cmake-tools/actions/runs/14145701868/job/40095177801?pr=4186

2025-04-16 20:15 UTC, hippo91 commented
@gcampbell-msft i am able to see the build log but for linux the only interesting thing is ```Warning: ls] 2025-04-07T11:17:46.863Z [warning] [proc] The command: /home/runner/work/_temp/-1604695791/cmake-3.18.3-Linux-x86_64/bin/cmake --build /home/runner/work/vscode-cmake-tools/vscode-cmake-tools/test/end-to-end-tests/single-root-ctest/project-folder/build -- exited with code: 1``` but i have no access to the inner log of this command.

It seems like the `cmake` command does not receive the correct config preset.
It is really weird because on my laptop (running debian) using `act`, the CI is successful.

2025-04-16 20:20 UTC, gcampbell-msft commented
@hippo91 I'm also interested in the failure for the Windows build. However, I also can't see any more information. I'll do my best to make time to investigate this sometime in the next week or so

2025-04-16 20:34 UTC, hippo91 commented
@gcampbell-msft the problem with windows is due to the fact i dumbly hardcoded path to /tmp which of course does not exist on windows. I should be able to fix this. However the only way for me to check windows execution is through the CI.

And for Linux in the CI for now i have no clue.

2025-04-17 18:32 UTC, hippo91 commented
@gcampbell-msft i think i fixed the windows problem. Can you relaunch the CI please?

2025-04-17 19:37 UTC, hippo91 commented
@gcampbell-msft surprisingly linux ci seems to be ok.

I removed an unused CMAKE variable for windows. It was generating what could be an error.

2025-04-20 09:37 UTC, hippo91 commented
@gcampbell-msft the linux part of the CI is ok but i'm struggling with the windows one (the macos one is failing in an unrelated test). If you could have a look it would be nice. Please tell me if i can do anything to help.

2025-06-24 16:05 UTC, gcampbell-msft commented
@hippo91 I updated to main and re-ran, it looks like the build for macos is failing even before running the tests, unfortunately I won't be able to investigate today, but we still hope to take this PR and we really appreciate your hard work!

2026-05-13 17:57 UTC, hanniavalera approved these changes

2026-05-13 18:00 UTC, snehara99 approved these changes

2026-05-13 18:03 UTC, hanniavalera approved these changes

2026-05-13 18:23 UTC, gcampbell-msft approved these changes

2026-05-13 18:23 UTC, merged

2026-05-15 08:40 UTC, hippo91 commented
@hanniavalera @gcampbell-msft thanks for your work. I am happy to see this finally merged!